version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install

  pre_build:
    commands:
      - echo Preparing for build...

  build:
    commands:
      - echo Building the project...
      - mvn clean package

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - target/*.jar
