version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install

  pre_build:
    commands:
      - echo Preparing for build...

  build:
    commands:
      - echo Building the project...
      - mvn clean package  # Este comando compila el proyecto y genera el archivo JAR/WAR

  post_build:
    commands:
      - echo Build completed.
      
artifacts:
  files:
    - target/*.jar  # O target/*.war, dependiendo del empaquetado de tu proyecto
