version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias..."
      - mvn install  # Instala todas las dependencias Maven
  pre_build:
    commands:
      - echo "Preparando para la construcción..."
      - mvn clean  # Limpia el proyecto antes de la construcción
  build:
    commands:
      - echo "Construyendo el proyecto..."
      - mvn package  # Empaqueta la aplicación
  post_build:
    commands:
      - echo "Construcción completada."
      - echo "Ejecutando pruebas o cualquier otro paso adicional si es necesario"

artifacts:
  files:
    - target/*.jar  # Especifica el artefacto que se generará, en este caso el JAR del proyecto Spring Boot
  discard-paths: yes
